"""empty message

Revision ID: 4a331e8cc17c
Revises: bbab11aef588
Create Date: 2025-02-19 11:46:37.918401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a331e8cc17c'
down_revision = 'bbab11aef588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('starships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('passanger', sa.String(), nullable=False),
    sa.Column('cargo_capacity', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('startships')
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starships_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'starships', ['starships_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('starships_id')

    op.create_table('startships',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('passanger', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cargo_capacity', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='startships_pkey')
    )
    op.drop_table('starships')
    # ### end Alembic commands ###
